name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2 

      - name: Build Docker image
        id: image_tag
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker build -t ${{ vars.ECR_REPO_URL }}:$IMAGE_TAG .
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Push Docker image to ECR
        run: |
          docker push ${{ vars.ECR_REPO_URL }}:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: argocd login
        uses: clowdhaus/argo-cd-action/@main
        env:
          ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ vars.ARGOCD_USERNAME }}   
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        with:
          version: 2.6.7
          command: login ${{ env.ARGOCD_SERVER }}
          options: --username ${{ env.ARGOCD_USERNAME }} --password ${{ env.ARGOCD_PASSWORD }} --insecure --skip-test-tls --http-retry-max 3 --grpc-web

      - name: check image tag
        run: |
          echo ${{ vars.ECR_REPO_URL }}:${{ needs.build.outputs.IMAGE_TAG }}

      - name: Set new image for helm parameter
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.6.7   
          command: app set counter-app -p image.repository=${{ vars.ECR_REPO_URL }}:$IMAGE_TAG
        

      - name: Sync app
        uses: clowdhaus/argo-cd-action/@main
        with: 
          version: 2.6.7
          command: app sync counter-app
